/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "primary":                    "rgb(var(--color-primary) / <alpha-value>)",
        "on-primary":                 "rgb(var(--color-on-primary) / <alpha-value>)",
        "primary-container":          "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary-container":       "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "primary-fixed":              "rgb(var(--color-primary-fixed, 218 226 253) / <alpha-value>)",
        "primary-fixed-dim":          "rgb(var(--color-primary-fixed-dim, 190 198 224) / <alpha-value>)",
        "on-primary-fixed":           "rgb(var(--color-on-primary-fixed, 19 27 46) / <alpha-value>)",
        "on-primary-fixed-variant":   "rgb(var(--color-on-primary-fixed-variant, 63 70 92) / <alpha-value>)",
        "secondary":                  "rgb(var(--color-secondary) / <alpha-value>)",
        "on-secondary":               "rgb(var(--color-on-secondary) / <alpha-value>)",
        "secondary-container":        "rgb(var(--color-secondary-container) / <alpha-value>)",
        "on-secondary-container":     "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "secondary-fixed":            "rgb(var(--color-secondary-container) / <alpha-value>)",
        "secondary-fixed-dim":        "rgb(var(--color-secondary-container) / <alpha-value>)",
        "on-secondary-fixed":         "rgb(var(--color-on-secondary) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--color-secondary) / <alpha-value>)",
        "tertiary":                   "rgb(var(--color-tertiary) / <alpha-value>)",
        "on-tertiary":                "rgb(var(--color-on-tertiary) / <alpha-value>)",
        "tertiary-container":         "rgb(var(--color-tertiary-container) / <alpha-value>)",
        "on-tertiary-container":      "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
        "surface":                    "rgb(var(--color-surface) / <alpha-value>)",
        "surface-dim":                "rgb(var(--color-surface-dim) / <alpha-value>)",
        "surface-bright":             "rgb(var(--color-surface-bright) / <alpha-value>)",
        "surface-container-lowest":   "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-container-low":      "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container":          "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-high":     "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest":  "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface-variant":            "rgb(var(--color-surface-variant) / <alpha-value>)",
        "on-surface":                 "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant":         "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "outline":                    "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant":            "rgb(var(--color-outline-variant) / <alpha-value>)",
        "inverse-surface":            "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "inverse-on-surface":         "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "inverse-primary":            "rgb(var(--color-inverse-primary) / <alpha-value>)",
        "background":                 "rgb(var(--color-background) / <alpha-value>)",
        "on-background":              "rgb(var(--color-on-background) / <alpha-value>)",
        "error":                      "rgb(var(--color-error) / <alpha-value>)",
        "on-error":                   "rgb(var(--color-on-error) / <alpha-value>)",
        "error-container":            "rgb(var(--color-error-container) / <alpha-value>)",
        "on-error-container":         "rgb(var(--color-on-error-container) / <alpha-value>)",
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.0625rem",
        "md": "0.1875rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(24px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.5s ease-out forwards",
        "spin-slow": "spin-slow 4s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
